Fix compilation error in mode --enable-strict
Log2() is not available in the redirection lib.

/usr/bin/ld: ./.libs/libpcsclite.so: undefined reference to `log_msg'

Log2() is used in SYS_RandomInt() that is not called by the redirection
library so no problem here.